[connection]
serial = "/dev/ttyACM0"

[[usb_device]]
# Use "lsusb list" to see details. Pick serial port over jtag port 
vid = "1a86"
pid = "55d3"

# vid = "303a"
# pid = "1001"

[flash]
# https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/spi-flash-modes.html
mode = "dio"
# https://www.waveshare.com/wiki/ESP32-C6-DEV-KIT-N8
size = "8MB"
frequency = "80MHz"

# Specify the offset of the partition table
partition_table_offset = 0x9020

# Specify the partition table file
partition_table = "partitions.csv"

# Specify the bootloader binary file
bootloader = "bootloader.bin"

# Other flash configuration options
#chip = "esp32c6"
# port = "/dev/ttyUSB0"
speed = 921600 # Set baud rate for flashing
# baudrate = 460800 # Set baud rate for communication
